/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miro_vidal.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miro_vidal.controller.MostrarEquipoController;
import miro_vidal.splash.SplashScreenMiroVidal;
import miro_vidal.db.AccesoDB;
/**
 *
 * @author wrd14n1
 */
public class PrincipalMiroVidalForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalMiroVidalForm
     */
    public PrincipalMiroVidalForm()  {
        initComponents();
        setLocationRelativeTo(null);
       /* try {
            JFrame.setDefaultLookAndFeelDecorated(true);
           // UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } */
        
        cargarlista();
        consulta();
        PanelNuevoPersonal.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMiro1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaequipos = new javax.swing.JList();
        btnseleccionar = new javax.swing.JButton();
        PanelMiro2 = new javax.swing.JPanel();
        JTabMiroVidal = new javax.swing.JTabbedPane();
        PanelAcCorrectiva = new javax.swing.JPanel();
        lblnbit = new javax.swing.JLabel();
        txtnbit = new javax.swing.JTextField();
        lblfechint = new javax.swing.JLabel();
        Fecha_Intervencion = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txttipomantto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnroordtrab = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtestatenfall = new javax.swing.JTextField();
        lbllugar = new javax.swing.JLabel();
        txtlugarintervencion = new javax.swing.JTextField();
        lbltipofalla = new javax.swing.JLabel();
        txttipofalla = new javax.swing.JTextField();
        lbldescripcionaccor = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblhorainicio = new javax.swing.JLabel();
        txthorainicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txthorafin = new javax.swing.JTextField();
        lblpersonal = new javax.swing.JLabel();
        txtpersonal = new javax.swing.JTextField();
        PanelPersonal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPersonal = new javax.swing.JTable();
        PanelDatosGenerales = new javax.swing.JPanel();
        txtdescripcion = new javax.swing.JTextField();
        lbldescripcion = new javax.swing.JLabel();
        lblubicacion = new javax.swing.JLabel();
        txtubicacion = new javax.swing.JTextField();
        lblmodelo_placa = new javax.swing.JLabel();
        txtmodelo_placa = new javax.swing.JTextField();
        lblmarca = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        lblfabricacion = new javax.swing.JLabel();
        txtfabricacion = new javax.swing.JTextField();
        lblnroserie = new javax.swing.JLabel();
        txtnroserie = new javax.swing.JTextField();
        lblcapacidad = new javax.swing.JLabel();
        txtcapacidad = new javax.swing.JTextField();
        lblpropietario = new javax.swing.JLabel();
        txtpropietario = new javax.swing.JTextField();
        lblestado = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        lblfechallegada = new javax.swing.JLabel();
        txtfechallegada = new javax.swing.JTextField();
        lblhorometro = new javax.swing.JLabel();
        txthorometro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblmotor = new javax.swing.JLabel();
        txtmmarca = new javax.swing.JTextField();
        txtmmodelo = new javax.swing.JTextField();
        txtmserie = new javax.swing.JTextField();
        lblperforadora = new javax.swing.JLabel();
        lblmotor1 = new javax.swing.JLabel();
        lblmotor2 = new javax.swing.JLabel();
        lblmotor3 = new javax.swing.JLabel();
        txtpmarca = new javax.swing.JTextField();
        txtpmodelo = new javax.swing.JTextField();
        txtpserie = new javax.swing.JTextField();
        lblmotor4 = new javax.swing.JLabel();
        lblmotor5 = new javax.swing.JLabel();
        lblmotor6 = new javax.swing.JLabel();
        PanelReFallas = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        RbEquipo = new javax.swing.JRadioButton();
        RbPersonal = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btncargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Miro Vidal");

        PanelMiro1.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipos"));

        jScrollPane2.setViewportView(listaequipos);

        btnseleccionar.setText("Seleccionar");
        btnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMiro1Layout = new javax.swing.GroupLayout(PanelMiro1);
        PanelMiro1.setLayout(PanelMiro1Layout);
        PanelMiro1Layout.setHorizontalGroup(
            PanelMiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiro1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(btnseleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelMiro1Layout.setVerticalGroup(
            PanelMiro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiro1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnseleccionar)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        PanelMiro2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lblnbit.setText("N° Bitácora:");

        lblfechint.setText("Fecha de Intervención:");

        jLabel1.setText("Tipo de Mantenimiento:");

        jLabel2.setText("N° de Orden de Trabajo:");

        jLabel3.setText("Estado de Atención de la Falla:");

        lbllugar.setText("Lugar de Intervención:");

        lbltipofalla.setText("Tipo de Falla:");

        lbldescripcionaccor.setText("Descripción:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        lblhorainicio.setText("Hora de Inicio:");

        jLabel4.setText("Hora de Finalización:");

        lblpersonal.setText("Código del Personal que hizo la intervención:");

        javax.swing.GroupLayout PanelAcCorrectivaLayout = new javax.swing.GroupLayout(PanelAcCorrectiva);
        PanelAcCorrectiva.setLayout(PanelAcCorrectivaLayout);
        PanelAcCorrectivaLayout.setHorizontalGroup(
            PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                        .addComponent(lblnbit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnbit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(lblfechint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fecha_Intervencion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttipomantto))
                    .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                        .addComponent(lbllugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlugarintervencion))
                    .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                        .addComponent(lbldescripcionaccor)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3))
                    .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                        .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(58, 58, 58)
                                .addComponent(txtnroordtrab, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtestatenfall, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                                .addComponent(lbltipofalla)
                                .addGap(18, 18, 18)
                                .addComponent(txttipofalla, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                                .addComponent(lblhorainicio)
                                .addGap(18, 18, 18)
                                .addComponent(txthorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txthorafin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                        .addComponent(lblpersonal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpersonal)))
                .addContainerGap())
        );
        PanelAcCorrectivaLayout.setVerticalGroup(
            PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAcCorrectivaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fecha_Intervencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblnbit)
                        .addComponent(txtnbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblfechint)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttipomantto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnroordtrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtestatenfall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllugar)
                    .addComponent(txtlugarintervencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipofalla)
                    .addComponent(txttipofalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldescripcionaccor)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhorainicio)
                    .addComponent(txthorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txthorafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PanelAcCorrectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpersonal)
                    .addComponent(txtpersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        JTabMiroVidal.addTab("Acción Correctiva", PanelAcCorrectiva);

        TablaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaPersonal);

        javax.swing.GroupLayout PanelPersonalLayout = new javax.swing.GroupLayout(PanelPersonal);
        PanelPersonal.setLayout(PanelPersonalLayout);
        PanelPersonalLayout.setHorizontalGroup(
            PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
            .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelPersonalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelPersonalLayout.setVerticalGroup(
            PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelPersonalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JTabMiroVidal.addTab("Personal", PanelPersonal);

        PanelDatosGenerales.setBorder(new javax.swing.border.MatteBorder(null));

        lbldescripcion.setText("Descripción:");

        lblubicacion.setText("Ubicación:");

        lblmodelo_placa.setText("Modelo/Placa:");

        lblmarca.setText("Marca:");

        lblfabricacion.setText("Año de Fabricación:");

        lblnroserie.setText("N° de Serie:");

        lblcapacidad.setText("Capacidad:");

        lblpropietario.setText("Propietario:");

        lblestado.setText("Estado:");

        lblfechallegada.setText("Fecha de Llegada:");

        lblhorometro.setText("Horómetro:");

        lblmotor.setText("Motor");

        lblperforadora.setText("Perforadora");

        lblmotor1.setText("Modelo:");

        lblmotor2.setText("Marca:");

        lblmotor3.setText("Serie:");

        lblmotor4.setText("Modelo:");

        lblmotor5.setText("Marca:");

        lblmotor6.setText("Serie:");

        javax.swing.GroupLayout PanelDatosGeneralesLayout = new javax.swing.GroupLayout(PanelDatosGenerales);
        PanelDatosGenerales.setLayout(PanelDatosGeneralesLayout);
        PanelDatosGeneralesLayout.setHorizontalGroup(
            PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosGeneralesLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(txtmarca))
                    .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblfabricacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfabricacion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblmodelo_placa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmodelo_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosGeneralesLayout.createSequentialGroup()
                                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcapacidad)
                                    .addComponent(lblestado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcapacidad)
                                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblnroserie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnroserie))
                            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblpropietario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpropietario))
                            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblmarca)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(lbldescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblhorometro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthorometro))
                    .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(lblubicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtubicacion))
                    .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(lblfechallegada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfechallegada))
                    .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(lblmotor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblperforadora)
                        .addGap(157, 157, 157))
                    .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblmotor3)
                                .addGap(18, 18, 18)
                                .addComponent(txtmserie))
                            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblmotor1)
                                .addGap(1, 1, 1)
                                .addComponent(txtmmodelo))
                            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblmotor2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosGeneralesLayout.createSequentialGroup()
                                    .addComponent(lblmotor4)
                                    .addGap(1, 1, 1)
                                    .addComponent(txtpmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                                    .addComponent(lblmotor6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtpserie, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(lblmotor5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpmarca)))))
                .addContainerGap())
        );
        PanelDatosGeneralesLayout.setVerticalGroup(
            PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescripcion)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhorometro)
                    .addComponent(txthorometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblubicacion)
                    .addComponent(txtubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodelo_placa)
                    .addComponent(txtmodelo_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmarca)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfabricacion)
                    .addComponent(txtfabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnroserie)
                    .addComponent(txtnroserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcapacidad)
                    .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpropietario)
                    .addComponent(txtpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblestado)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfechallegada)
                    .addComponent(txtfechallegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmotor)
                    .addComponent(lblperforadora))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmotor2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmotor1)
                            .addComponent(txtmmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmotor3)
                            .addComponent(txtmserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDatosGeneralesLayout.createSequentialGroup()
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmotor5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmotor4)
                            .addComponent(txtpmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmotor6)
                            .addComponent(txtpserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        JTabMiroVidal.addTab("Datos Generales", PanelDatosGenerales);

        javax.swing.GroupLayout PanelReFallasLayout = new javax.swing.GroupLayout(PanelReFallas);
        PanelReFallas.setLayout(PanelReFallasLayout);
        PanelReFallasLayout.setHorizontalGroup(
            PanelReFallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        PanelReFallasLayout.setVerticalGroup(
            PanelReFallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        JTabMiroVidal.addTab("Reporte de Fallas", PanelReFallas);

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");

        jButton3.setText("Eliminar");

        jButton4.setText("Guardar Cambios");

        RbEquipo.setText("Equipo Pesado");

        RbPersonal.setText("Personal");

        jLabel5.setText("Seleccione una opción si quiere agregar un nuevo dato.");

        javax.swing.GroupLayout PanelMiro2Layout = new javax.swing.GroupLayout(PanelMiro2);
        PanelMiro2.setLayout(PanelMiro2Layout);
        PanelMiro2Layout.setHorizontalGroup(
            PanelMiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiro2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTabMiroVidal)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMiro2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelMiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMiro2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMiro2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(RbEquipo)
                                .addGap(18, 18, 18)
                                .addComponent(RbPersonal)
                                .addGap(18, 18, 18)
                                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        PanelMiro2Layout.setVerticalGroup(
            PanelMiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiro2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevo)
                    .addComponent(RbEquipo)
                    .addComponent(RbPersonal)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTabMiroVidal, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMiro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        btncargar.setText("Cargar Datos");
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMiro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PanelMiro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelMiro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncargar)
                        .addGap(18, 18, 18)
                        .addComponent(PanelMiro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarActionPerformed
        
        MostrarEquipoController controller = new MostrarEquipoController();
        int index= listaequipos.getSelectedIndex();
        String equipo;
        if (index >= 0 && PanelDatosGenerales.isShowing()){
            equipo=listaequipos.getSelectedValue().toString();
            try {
                controller.MostrarEquipo(equipo);
            } catch (SQLException ex) {
                Logger.getLogger(PrincipalMiroVidalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                txtubicacion.setText(controller.MostrarEquipo(equipo)[0]);
                txtdescripcion.setText(controller.MostrarEquipo(equipo)[1]);
                txtmodelo_placa.setText(controller.MostrarEquipo(equipo)[2]);
                txtmarca.setText(controller.MostrarEquipo(equipo)[3]);
                txtfabricacion.setText(controller.MostrarEquipo(equipo)[4]);
                txtnroserie.setText(controller.MostrarEquipo(equipo)[5]);
                txtcapacidad.setText(controller.MostrarEquipo(equipo)[6]);
                txtpropietario.setText(controller.MostrarEquipo(equipo)[7]);
                txtestado.setText(controller.MostrarEquipo(equipo)[8]);
                txtfechallegada.setText(controller.MostrarEquipo(equipo)[9]);
                txthorometro.setText(controller.MostrarEquipo(equipo)[10]);
                
            } catch (SQLException ex) {
                Logger.getLogger(PrincipalMiroVidalForm.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }        
    }//GEN-LAST:event_btnseleccionarActionPerformed

    private void btncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarActionPerformed
      cargarlista();
    }//GEN-LAST:event_btncargarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
      NuevoEquipoView equipo = new NuevoEquipoView();
      NuevoPersonalView personal = new NuevoPersonalView();
        if (RbEquipo.isSelected() && RbPersonal.isSelected()==false){
          equipo.setVisible(true);
          equipo.pack();
      } else {
          if (RbPersonal.isSelected()&& RbEquipo.isSelected()==false){
              
              personal.setVisible(true);
              personal.pack();
          } else {
              JOptionPane.showMessageDialog(this,"Está seleccionado ambos campos, sólo debe seleccionar uno.");
          }
      }  
    }//GEN-LAST:event_btnnuevoActionPerformed

  public void cargarlista ()  {
 
        MostrarEquipoController controlador = new MostrarEquipoController();
        DefaultListModel modelo = new DefaultListModel();
        int i=0;
        while(i<50){
           try {
               modelo.addElement(controlador.CargarEquipo()[i]);
           } catch (SQLException ex) {
               Logger.getLogger(PrincipalMiroVidalForm.class.getName()).log(Level.SEVERE, null, ex);
           }
           i++;
        } 
        listaequipos.setModel(modelo);        
  }
  
  public void consulta(){
      try {
            DefaultTableModel modelo = new DefaultTableModel();
            this.TablaPersonal.setModel(modelo);
            Connection con = (Connection)AccesoDB.getConnection();
            Statement st = (Statement)con.createStatement();
                        
            ResultSet rst = st.executeQuery("select * from personal");
            ResultSetMetaData resMetDat = rst.getMetaData();
            int CantidadColumnas = resMetDat.getColumnCount();
            
             modelo.addColumn("Código");
             modelo.addColumn("Apellidos");
             modelo.addColumn("Nombres");
             modelo.addColumn("Cargo");
             modelo.addColumn("Fecha de Nacimiento");
             modelo.addColumn("Equipo Autorizado");
             modelo.addColumn("Fecha de Ingreso");
             modelo.addColumn("Años de Experiencia");
             modelo.addColumn("Trabajador Pertenece a");
             modelo.addColumn("Número Telefónico");
             modelo.addColumn("Estado Actual");
         
            /*
            for (int i = 1; i <= CantidadColumnas ; i++) {
                modelo.addColumn(resMetDat.getColumnLabel(i));
            }
            */
            while (rst.next()) {                
                Object[] fila = new Object[CantidadColumnas];
                for (int i = 0; i < CantidadColumnas; i++) {
                    fila[i]=rst.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            rst.close();
            con.close();
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
      
  }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Thread (new SplashScreenMiroVidal()).start();      
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalMiroVidalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalMiroVidalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalMiroVidalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalMiroVidalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new PrincipalMiroVidalForm().setVisible(false);             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha_Intervencion;
    private javax.swing.JTabbedPane JTabMiroVidal;
    private javax.swing.JPanel PanelAcCorrectiva;
    private javax.swing.JPanel PanelDatosGenerales;
    private javax.swing.JPanel PanelMiro1;
    private javax.swing.JPanel PanelMiro2;
    private javax.swing.JPanel PanelPersonal;
    private javax.swing.JPanel PanelReFallas;
    private javax.swing.JRadioButton RbEquipo;
    private javax.swing.JRadioButton RbPersonal;
    private javax.swing.JTable TablaPersonal;
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblcapacidad;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lbldescripcionaccor;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblfabricacion;
    private javax.swing.JLabel lblfechallegada;
    private javax.swing.JLabel lblfechint;
    private javax.swing.JLabel lblhorainicio;
    private javax.swing.JLabel lblhorometro;
    private javax.swing.JLabel lbllugar;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lblmodelo_placa;
    private javax.swing.JLabel lblmotor;
    private javax.swing.JLabel lblmotor1;
    private javax.swing.JLabel lblmotor2;
    private javax.swing.JLabel lblmotor3;
    private javax.swing.JLabel lblmotor4;
    private javax.swing.JLabel lblmotor5;
    private javax.swing.JLabel lblmotor6;
    private javax.swing.JLabel lblnbit;
    private javax.swing.JLabel lblnroserie;
    private javax.swing.JLabel lblperforadora;
    private javax.swing.JLabel lblpersonal;
    private javax.swing.JLabel lblpropietario;
    private javax.swing.JLabel lbltipofalla;
    private javax.swing.JLabel lblubicacion;
    private javax.swing.JList listaequipos;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtestatenfall;
    private javax.swing.JTextField txtfabricacion;
    private javax.swing.JTextField txtfechallegada;
    private javax.swing.JTextField txthorafin;
    private javax.swing.JTextField txthorainicio;
    private javax.swing.JTextField txthorometro;
    private javax.swing.JTextField txtlugarintervencion;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmmarca;
    private javax.swing.JTextField txtmmodelo;
    private javax.swing.JTextField txtmodelo_placa;
    private javax.swing.JTextField txtmserie;
    private javax.swing.JTextField txtnbit;
    private javax.swing.JTextField txtnroordtrab;
    private javax.swing.JTextField txtnroserie;
    private javax.swing.JTextField txtpersonal;
    private javax.swing.JTextField txtpmarca;
    private javax.swing.JTextField txtpmodelo;
    private javax.swing.JTextField txtpropietario;
    private javax.swing.JTextField txtpserie;
    private javax.swing.JTextField txttipofalla;
    private javax.swing.JTextField txttipomantto;
    private javax.swing.JTextField txtubicacion;
    // End of variables declaration//GEN-END:variables
}
